apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: {{ .Values.containers.port }}
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.containers.env.DB_USERNAME.name }}
              key: {{ .Values.containers.env.DB_USERNAME.key }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.containers.env.DB_PASSWORD.name }}
              key: {{ .Values.containers.env.DB_PASSWORD.key }}